const escapeHtml = (value = '') => String(value).replace(/[&<>"']/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[char]));

const arrow = '<svg viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="M5 12h14m-6-6 6 6-6 6" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"/></svg>';
const check = '<svg viewBox="0 0 20 20" fill="none" aria-hidden="true"><path d="m4 10 4 4 8-8" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"/></svg>';

export function renderApexLandingHtml(jobs) {
  const examples = Object.values(jobs).slice(0, 4);
  return `<!DOCTYPE html>
<html lang="en-AU">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="Aigents helps engineering students show their skills, prepare with practical AI tools and connect with employers for paid project work.">
  <meta name="theme-color" content="#2457e8">
  <title>Aigents — Paid engineering work while you study</title>
  <link rel="canonical" href="https://aigents.au/">
  <style>
    :root{--ink:#15243c;--muted:#5f6b80;--blue:#2457e8;--blue-dark:#1644c8;--lime:#d9f46b;--line:#dfe5ef;--canvas:#f5f7fb;--white:#fff;--radius:22px;font-family:Inter,Arial,Helvetica,sans-serif;color:var(--ink);font-synthesis:none}
    *{box-sizing:border-box}html{scroll-behavior:smooth;scroll-padding-top:105px}body{margin:0;background:var(--white);font-size:16px;line-height:1.6;-webkit-font-smoothing:antialiased}button,input{font:inherit}a{color:inherit}button,a{-webkit-tap-highlight-color:transparent}button{cursor:pointer}svg{display:block;width:22px;height:22px;flex:none}::selection{background:var(--lime);color:var(--ink)}:focus-visible{outline:3px solid var(--blue);outline-offset:5px}h1,h2,h3,p{margin:0}h1,h2,h3{line-height:1.12;letter-spacing:-.045em}h2{font-size:clamp(32px,3.8vw,48px);font-weight:650}h3{font-size:22px;letter-spacing:-.025em}.wrap{max-width:1240px;padding:0 40px;margin:auto}.skip{position:fixed;top:-100px;left:16px;z-index:200;background:white;padding:12px 20px;border:2px solid var(--blue)}.skip:focus{top:12px}
    .site-header{position:sticky;top:0;z-index:50;background:rgba(255,255,255,.97);border-bottom:1px solid var(--line)}.nav{height:86px;display:flex;align-items:center;justify-content:space-between;gap:28px}.brand{text-decoration:none;display:inline-flex;align-items:center;gap:9px;flex:none}.brand-word{font-size:30px;font-weight:800;letter-spacing:-1.9px;line-height:1}.brand-word span{color:var(--blue)}.brand-mark{height:25px;width:25px;display:grid;place-items:center;background:var(--lime);border-radius:7px;color:var(--ink);font-size:24px;line-height:1;font-weight:600}.nav-links{display:flex;align-items:center;gap:30px}.nav-link{font-size:14px;font-weight:600;text-decoration:none}.nav-link:hover{color:var(--blue)}.nav-cta{display:flex;align-items:center;gap:20px}.btn{display:inline-flex;align-items:center;justify-content:center;gap:12px;min-height:54px;padding:14px 22px;border:1px solid transparent;border-radius:9px;font-size:15px;line-height:1.35;font-weight:650;text-decoration:none;transition:background .18s,transform .18s,color .18s}.btn:hover{transform:translateY(-2px)}.btn-primary{background:var(--blue);color:white}.btn-primary:hover{background:var(--blue-dark)}.btn-secondary{background:white;border-color:var(--line);color:var(--ink)}.btn-secondary:hover{background:var(--canvas)}.btn-light{background:var(--lime);color:var(--ink)}.btn-light:hover{background:#e4ff84}.nav .btn{min-height:45px;padding:11px 17px;font-size:14px}.menu-button{display:none;width:44px;height:44px;align-items:center;justify-content:center;background:var(--canvas);border:1px solid var(--line);border-radius:8px}
    .hero{padding:76px 0 62px}.hero-grid{display:grid;grid-template-columns:1.05fr 1fr;gap:68px;align-items:center}.eyebrow{display:flex;align-items:center;gap:10px;font-size:12px;letter-spacing:.12em;font-weight:750;text-transform:uppercase;color:var(--blue)}.eyebrow:before{content:'';width:24px;height:2px;background:currentColor}.hero h1{font-size:clamp(46px,5.3vw,69px);font-weight:650;line-height:1.035;margin:23px 0 24px;letter-spacing:-.06em}.hero h1 span{display:block;color:var(--blue)}.hero-description{color:var(--muted);font-size:18px;line-height:1.7;max-width:470px}.hero-actions{display:flex;align-items:center;gap:12px;margin-top:30px}.hero-note{margin-top:20px;display:flex;align-items:center;gap:8px;font-size:13px;color:var(--muted)}.hero-note svg{width:17px;height:17px;color:var(--blue)}
    .profile-stage{position:relative;padding:28px;border-radius:26px;background:#eaf0ff}.stage-top{display:flex;align-items:center;justify-content:space-between;gap:12px;margin-bottom:18px}.stage-top p{font-size:12px;text-transform:uppercase;letter-spacing:.1em;font-weight:750;color:#4c6091}.stage-pagination{display:flex;gap:5px}.stage-pagination i{width:5px;height:5px;border-radius:50%;background:#b3c4ec}.stage-pagination i:first-child{width:17px;border-radius:3px;background:var(--blue)}.profile-card{background:white;border:1px solid #dbe3f7;border-radius:15px;padding:26px;box-shadow:0 12px 35px #25438c0b}.profile-header{display:flex;align-items:center;gap:14px;padding-bottom:22px;border-bottom:1px solid var(--line)}.avatar{width:57px;height:57px;border-radius:50%;background:#dae5ff;display:grid;place-items:center;font-size:19px;font-weight:650;color:var(--blue);flex:none}.profile-header h2{font-size:20px;letter-spacing:-.035em;margin-bottom:4px}.profile-header p{font-size:13px;color:var(--muted)}.profile-caption{font-size:11px;color:var(--muted);font-weight:500}.profile-label{font-size:11px;letter-spacing:.1em;color:var(--muted);font-weight:700;margin:20px 0 10px}.skill-list{display:flex;flex-wrap:wrap;gap:7px}.skill-list span{font-size:12px;padding:5px 10px;background:var(--canvas);border:1px solid #e8edf5;border-radius:5px}.project-preview{margin-top:19px;background:#f6f8fd;border:1px solid #e8edf5;border-radius:10px;overflow:hidden}.project-preview-top{display:flex;justify-content:space-between;align-items:center;padding:14px 15px 0;gap:8px}.project-preview-top h3{font-size:13px;font-weight:600;letter-spacing:-.015em}.project-preview-top span{font-size:10px;padding:3px 7px;border-radius:4px;color:#375214;background:#e7f4ce;white-space:nowrap}.chart{width:100%;height:94px;padding:6px 13px 0}.chart svg{width:100%;height:100%}.project-caption{padding:3px 15px 14px;font-size:11px;color:var(--muted)}.profile-footer{display:flex;align-items:center;justify-content:space-between;gap:10px;margin-top:20px}.profile-footer span{font-size:12px;color:var(--muted)}.profile-footer a{display:inline-flex;align-items:center;gap:7px;color:var(--blue);font-weight:650;font-size:12px;text-decoration:none}.profile-footer svg{width:16px;height:16px}.ai-note{margin:16px 0 0;display:flex;align-items:center;gap:12px;padding:14px 16px;background:var(--ink);border-radius:10px;color:white}.ai-icon{width:32px;height:32px;border-radius:8px;background:var(--lime);color:var(--ink);display:grid;place-items:center;flex:none}.ai-note strong{display:block;font-size:12px;line-height:1.4;font-weight:600}.ai-note p{font-size:11px;line-height:1.5;color:#c3cede;margin-top:2px}
    .clarity-strip{background:var(--canvas);border-top:1px solid var(--line);border-bottom:1px solid var(--line)}.clarity-inner{display:flex;align-items:center;justify-content:space-between;gap:28px;min-height:99px}.clarity-intro{font-size:13px;line-height:1.55;color:var(--muted);max-width:200px}.clarity-items{display:flex;align-items:center;justify-content:space-between;gap:45px}.clarity-item{display:flex;gap:10px;align-items:center;font-size:14px;font-weight:600}.clarity-item svg{width:19px;height:19px;color:var(--blue)}
    .section{padding:92px 0}.section-head{display:flex;align-items:flex-end;justify-content:space-between;gap:40px;margin-bottom:39px}.section-head .eyebrow{margin-bottom:17px}.section-description{max-width:355px;font-size:16px;color:var(--muted)}.steps{display:grid;grid-template-columns:repeat(3,1fr);gap:36px}.step{border-top:1px solid #c9d3e3;padding-top:24px}.step-number{display:inline-flex;align-items:center;justify-content:center;width:36px;height:36px;border-radius:50%;background:var(--canvas);color:var(--blue);font-size:12px;font-weight:700;margin-bottom:27px}.step h3{font-size:23px;margin-bottom:13px}.step p{font-size:15px;color:var(--muted);max-width:310px;line-height:1.75}.text-link{display:inline-flex;align-items:center;gap:8px;text-decoration:none;font-weight:650;color:var(--blue);font-size:14px;margin-top:19px}.text-link svg{width:18px;height:18px}.text-link:hover{text-decoration:underline;text-underline-offset:4px}
    .audience-section{background:var(--canvas);border-top:1px solid var(--line);border-bottom:1px solid var(--line)}.audience-grid{display:grid;grid-template-columns:1fr 1fr;gap:64px;align-items:center}.audience-heading h2{max-width:440px}.audience-heading>.eyebrow{margin-bottom:19px}.audience-tabs{display:inline-flex;border:1px solid #d6deeb;border-radius:9px;padding:4px;gap:4px;background:white;margin-top:28px}.audience-tabs button{border:0;border-radius:6px;background:transparent;padding:10px 21px;font-weight:600;color:var(--muted);font-size:14px}.audience-tabs button[aria-selected="true"]{background:var(--blue);color:white}.audience-panel{background:white;border:1px solid var(--line);border-radius:var(--radius);padding:34px}.audience-panel[hidden]{display:none}.panel-eyebrow{font-size:12px;color:var(--blue);font-weight:700;margin-bottom:14px}.audience-panel h3{font-size:27px;margin-bottom:18px}.benefits{list-style:none;padding:0;margin:0 0 25px}.benefits li{display:flex;align-items:flex-start;gap:11px;color:var(--muted);font-size:15px;margin-top:13px;line-height:1.65}.benefits svg{color:var(--blue);width:18px;height:18px;margin-top:3px}.audience-panel .btn{min-height:48px;font-size:14px}
    .example-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:16px}.example{display:grid;grid-template-columns:46px 1fr 30px;gap:17px;align-items:start;padding:25px;border:1px solid var(--line);border-radius:14px;text-decoration:none;transition:border-color .2s,background .2s}.example:hover{border-color:#a7baf3;background:#fbfcff}.company-initial{height:44px;width:44px;display:grid;place-items:center;border-radius:10px;background:#eaf0ff;font-size:19px;color:var(--blue);font-weight:700}.example:nth-child(2) .company-initial{background:#e6efce;color:#496314}.example:nth-child(3) .company-initial{background:#f9e8da;color:#9d5a2a}.example:nth-child(4) .company-initial{background:#e3eff0;color:#377078}.example h3{font-size:18px;letter-spacing:-.02em;margin:3px 0 7px}.example p{font-size:13px;color:var(--muted);line-height:1.6}.example .example-label{display:block;margin-top:13px;font-size:11px;font-weight:650;color:var(--blue)}.example>svg{margin-top:10px;color:var(--muted)}.examples-note{font-size:12px;color:var(--muted);margin-top:19px;max-width:800px;line-height:1.6}
    .faq-section{padding-top:0}.faq-grid{display:grid;grid-template-columns:1fr 1.3fr;gap:80px}.faq-intro p{color:var(--muted);margin-top:18px;font-size:15px;max-width:300px}.faq-list details{border-bottom:1px solid var(--line)}.faq-list details:first-child{border-top:1px solid var(--line)}.faq-list summary{list-style:none;cursor:pointer;display:flex;align-items:center;justify-content:space-between;gap:20px;font-size:15px;font-weight:650;padding:21px 0}.faq-list summary::-webkit-details-marker{display:none}.faq-list summary:after{content:'+';color:var(--blue);font-size:23px;font-weight:400}.faq-list details[open] summary:after{content:'−'}.faq-list details p{font-size:14px;color:var(--muted);padding:0 30px 22px 0;line-height:1.75}.faq-list details a{color:var(--blue)}
    .closing{background:var(--blue);color:white;border-radius:24px;padding:49px 53px;display:flex;align-items:center;justify-content:space-between;gap:40px;margin-bottom:72px}.closing h2{font-size:37px;max-width:480px}.closing p{font-size:15px;color:#dae4ff;margin-top:12px}.closing .btn{flex:none}.footer{border-top:1px solid var(--line);padding:32px 0}.footer-inner{display:flex;align-items:center;justify-content:space-between;gap:24px}.footer .brand-word{font-size:25px}.footer-description{color:var(--muted);font-size:12px;margin-top:10px}.footer-links{display:flex;align-items:center;gap:26px}.footer-links a{font-size:13px;color:var(--muted);text-decoration:none}.footer-links a:hover{color:var(--blue)}
    @media(min-width:1500px){.hero{padding-top:90px;padding-bottom:80px}}
    @media(max-width:1100px){.wrap{padding:0 28px}.nav-links{gap:20px}.nav-cta>.nav-link{display:none}.hero-grid{gap:34px}.hero h1{font-size:57px}.hero-description{font-size:17px}.hero-actions{align-items:stretch;flex-wrap:wrap}.profile-stage{padding:22px}.profile-card{padding:20px}.clarity-items{gap:23px}.clarity-item{font-size:12px}.clarity-intro{font-size:12px}.audience-grid{gap:38px}.faq-grid{gap:44px}}
    @media(max-width:800px){.nav{height:74px;gap:15px}.brand-word{font-size:28px}.nav-links{display:none;position:absolute;left:0;right:0;top:73px;background:white;border-bottom:1px solid var(--line);padding:22px 28px;flex-direction:column;align-items:flex-start;gap:20px}.nav-links.open{display:flex}.menu-button{display:flex}.nav-cta{gap:10px}.nav .btn{font-size:12px;padding:10px 12px}.nav .btn svg{display:none}.hero{padding:44px 0}.hero-grid{gap:38px;grid-template-columns:1fr}.hero h1{font-size:clamp(47px,8vw,65px);max-width:610px}.hero-description{max-width:570px}.hero-actions{flex-wrap:nowrap;align-items:center}.hero-note{font-size:12px}.profile-stage{max-width:540px;width:100%;margin:auto}.profile-card{padding:25px}.chart{height:115px}.clarity-inner{padding-top:23px;padding-bottom:23px;display:block}.clarity-intro{max-width:none;margin-bottom:17px}.clarity-items{justify-content:flex-start;gap:22px;flex-wrap:wrap}.clarity-item{font-size:12px}.section{padding:63px 0}.section-head{display:block;margin-bottom:30px}.section-description{max-width:540px;margin-top:20px;font-size:15px}.steps{gap:23px}.step h3{font-size:20px}.step p{font-size:14px}.step-number{margin-bottom:22px}.audience-grid{grid-template-columns:1fr;gap:28px}.audience-heading h2{max-width:570px}.audience-panel{padding:28px}.example-grid{grid-template-columns:1fr}.faq-section{padding-top:0}.faq-grid{grid-template-columns:1fr;gap:28px}.faq-intro p{max-width:none}.closing{margin-bottom:50px;padding:35px;display:block}.closing h2{font-size:33px}.closing .btn{margin-top:25px}.footer-inner{align-items:flex-start}.footer-links{gap:15px;flex-wrap:wrap;justify-content:flex-end;max-width:240px}}
    @media(max-width:480px){.wrap{padding:0 21px}.nav{gap:8px}.brand-word{font-size:26px}.brand-mark{width:21px;height:21px;font-size:21px}.nav .btn{font-size:11px;min-height:42px}.nav-cta{gap:7px}.menu-button{height:42px;width:39px}.hero h1{font-size:48px;letter-spacing:-.065em}.hero-description{font-size:16px}.eyebrow{font-size:10px;letter-spacing:.1em}.hero-actions{gap:9px}.hero-actions .btn{padding:13px 16px;font-size:13px;min-height:51px}.hero-actions svg{width:18px;height:18px}.hero-note{align-items:flex-start;font-size:11px}.profile-stage{padding:18px;border-radius:19px}.stage-top p{font-size:10px}.profile-card{padding:18px}.profile-header h2{font-size:18px}.profile-header p{font-size:11px}.avatar{width:47px;height:47px;font-size:16px}.profile-footer span{font-size:10px}.profile-footer a{font-size:11px}.ai-note{padding:12px}.ai-note p{font-size:10px}.clarity-items{display:grid;grid-template-columns:1fr;gap:12px}.clarity-item{font-size:13px}.steps{grid-template-columns:1fr;gap:28px}.step{display:grid;grid-template-columns:36px 1fr;column-gap:17px;padding-top:22px}.step-number{grid-row:1/4;margin:0}.step h3{margin:4px 0 12px}.step p{max-width:none}.step .text-link{grid-column:2}.section-head h2{font-size:34px}.audience-panel{padding:24px}.audience-panel h3{font-size:25px}.audience-tabs{display:flex}.audience-tabs button{flex:1;padding:10px 13px}.example{padding:20px;grid-template-columns:40px 1fr 20px;gap:13px}.company-initial{width:39px;height:39px;font-size:16px}.example h3{font-size:17px}.example p{font-size:12px}.examples-note{font-size:11px}.closing{padding:28px;border-radius:18px}.closing h2{font-size:31px}.footer-inner{display:block}.footer-links{justify-content:flex-start;max-width:none;margin-top:22px}.faq-list summary{font-size:14px}}
    @media(prefers-reduced-motion:reduce){html{scroll-behavior:auto}.btn,.example{transition:none}.btn:hover{transform:none}}
  </style>
</head>
<body>
  <a class="skip" href="#main">Skip to content</a>
  <header class="site-header">
    <div class="wrap nav">
      <a class="brand" href="/" aria-label="Aigents home"><span class="brand-word">aigents<span>.</span></span><span class="brand-mark" aria-hidden="true">✳</span></a>
      <nav class="nav-links" id="main-navigation" aria-label="Main navigation">
        <a class="nav-link" href="#how-it-works">How it works</a>
        <a class="nav-link" href="#for-you">For students</a>
        <a class="nav-link" href="#examples">See examples</a>
        <a class="nav-link" href="/signin">Sign in</a>
      </nav>
      <div class="nav-cta"><a class="nav-link" href="/employers">For employers</a><a class="btn btn-primary" href="/build">Create your profile ${arrow}</a><button class="menu-button" type="button" aria-label="Open navigation" aria-expanded="false" aria-controls="main-navigation"><svg viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="M5 7h14M5 12h14M5 17h14" stroke="currentColor" stroke-width="1.7" stroke-linecap="round"/></svg></button></div>
    </div>
  </header>
  <main id="main">
    <section class="hero">
      <div class="wrap hero-grid">
        <div class="hero-copy">
          <p class="eyebrow">Engineering students. Real opportunities.</p>
          <h1>Get paid to do<span>real engineering.</span></h1>
          <p class="hero-description">Aigents helps engineering students find paid project work while they study. Build a clear skills profile, prepare with practical AI tools and connect with employers.</p>
          <div class="hero-actions"><a class="btn btn-primary" href="/build">I'm a student ${arrow}</a><a class="btn btn-secondary" href="/employers">I'm hiring ${arrow}</a></div>
          <p class="hero-note">${check} Your profile starts private. Share it when you're ready.</p>
        </div>
        <div class="profile-stage" aria-label="Example of a student profile and project">
          <div class="stage-top"><p>More than a CV. Show what you can do.</p><span class="stage-pagination" aria-hidden="true"><i></i><i></i><i></i></span></div>
          <div class="profile-card">
            <div class="profile-header"><div class="avatar" aria-hidden="true">AT</div><div><h2>Alex Taylor</h2><p>Mechanical engineering student</p><span class="profile-caption">Illustrative student profile</span></div></div>
            <p class="profile-label">SKILLS THAT YOU CAN PUT TO WORK</p>
            <div class="skill-list"><span>Python</span><span>CAD &amp; design</span><span>Data analysis</span><span>AI tools</span></div>
            <div class="project-preview"><div class="project-preview-top"><h3>Sensor data analysis</h3><span>Example project</span></div>
              <div class="chart"><svg viewBox="0 0 340 90" role="img" aria-label="Illustrative sensor readings chart"><path d="M0 18H340M0 45H340M0 72H340" stroke="#dfe5ef" stroke-width="1"/><path d="M0 61 16 65 32 55 48 60 64 37 80 49 96 42 112 59 128 52 144 30 160 42 176 36 192 48 208 40 224 19 240 34 256 26 272 35 288 13 304 25 320 19 340 9" stroke="#2457e8" stroke-width="2.5" fill="none" stroke-linecap="round" stroke-linejoin="round"/><path d="M0 77 48 72 96 65 144 59 192 51 240 45 288 37 340 29" stroke="#9daccc" stroke-width="1.5" stroke-dasharray="4 4" fill="none"/></svg></div>
              <p class="project-caption">Turn raw readings into a clear engineering report.</p>
            </div>
            <div class="profile-footer"><span>Skills + projects + experience</span><a href="/build">Build your profile ${arrow}</a></div>
          </div>
          <div class="ai-note"><span class="ai-icon" aria-hidden="true">✳</span><div><strong>Your engineering knowledge, supported by AI.</strong><p>Tools to help with coding, analysis and documentation.</p></div></div>
        </div>
      </div>
    </section>
    <div class="clarity-strip"><div class="wrap clarity-inner"><p class="clarity-intro">A practical bridge between<br>university and industry.</p><div class="clarity-items"><div class="clarity-item">${check} Build a useful profile</div><div class="clarity-item">${check} Develop practical AI skills</div><div class="clarity-item">${check} Explore paid project work</div></div></div></div>
    <section class="section" id="how-it-works"><div class="wrap">
      <div class="section-head"><div><p class="eyebrow">How Aigents works</p><h2>A clearer path to<br>your first engineering role.</h2></div><p class="section-description">Your university projects are a starting point. We help you show employers how those skills can contribute to real work.</p></div>
      <div class="steps">
        <article class="step"><span class="step-number">01</span><h3>Show your skills.</h3><p>Create a student profile with your course, technical skills and a project you're proud of.</p><a class="text-link" href="/build">Create your profile ${arrow}</a></article>
        <article class="step"><span class="step-number">02</span><h3>Prepare for real work.</h3><p>See how AI can support engineering tasks, from analysing data to writing code and preparing reports.</p><a class="text-link" href="#examples">Explore project examples ${arrow}</a></article>
        <article class="step"><span class="step-number">03</span><h3>Connect with employers.</h3><p>Choose to share your profile with employers. Project enquiries sent to you appear in your profile inbox.</p><a class="text-link" href="/signin">Sign in to your profile ${arrow}</a></article>
      </div>
    </div></section>
    <section class="section audience-section" id="for-you"><div class="wrap audience-grid">
      <div class="audience-heading"><p class="eyebrow">Two sides. One good fit.</p><h2>Students ready to learn.<br>Teams with work to do.</h2><div class="audience-tabs" role="tablist" aria-label="Choose your perspective"><button id="student-tab" type="button" role="tab" aria-selected="true" aria-controls="student-panel">I'm a student</button><button id="employer-tab" type="button" role="tab" aria-selected="false" aria-controls="employer-panel" tabindex="-1">I'm an employer</button></div></div>
      <div class="audience-panel" id="student-panel" role="tabpanel" aria-labelledby="student-tab" tabindex="0"><p class="panel-eyebrow">FOR ENGINEERING STUDENTS</p><h3>Turn what you're learning<br>into something employers can see.</h3><ul class="benefits"><li>${check}<span>Put your coursework, projects and technical skills in one place.</span></li><li>${check}<span>Explain the work you can do, with practical project examples.</span></li><li>${check}<span>Start a conversation about paid experience in your field.</span></li></ul><a class="btn btn-primary" href="/build">Create your student profile ${arrow}</a></div>
      <div class="audience-panel" id="employer-panel" role="tabpanel" aria-labelledby="employer-tab" tabindex="0" hidden><p class="panel-eyebrow">FOR ENGINEERING EMPLOYERS</p><h3>Find a student who can<br>contribute to your next project.</h3><ul class="benefits"><li>${check}<span>Explore skills and project examples beyond a traditional CV.</span></li><li>${check}<span>Discuss support for analysis, coding and technical documentation.</span></li><li>${check}<span>Agree on a suitable scope, supervision and paid work arrangement.</span></li></ul><a class="btn btn-primary" href="/employers">Tell us about your project ${arrow}</a></div>
    </div></section>
    <section class="section" id="examples"><div class="wrap">
      <div class="section-head"><div><p class="eyebrow">See what that looks like</p><h2>Real-world roles.<br>Practical project examples.</h2></div><p class="section-description">Explore example profiles tailored to engineering roles, and see how a student's skills can support the work.</p></div>
      <div class="example-grid">${examples.map(job => `<a class="example" href="/p/${encodeURIComponent(job.company.slug)}" aria-label="Explore ${escapeHtml(job.company.name)} role example"><span class="company-initial" aria-hidden="true">${escapeHtml(job.company.name.charAt(0))}</span><div><h3>${escapeHtml(job.company.name)}</h3><p>${escapeHtml(job.role.title)}</p><span class="example-label">EXPLORE ROLE EXAMPLE</span></div>${arrow}</a>`).join('')}</div>
      <p class="examples-note">These are illustrative, role-specific examples. Company names describe the roles being explored and do not imply a partnership or a current placement offer.</p>
    </div></section>
    <section class="section faq-section" id="questions"><div class="wrap faq-grid"><div class="faq-intro"><h2>A few things<br>you might be wondering.</h2><p>A clear starting point, whether you're studying engineering or looking for project support.</p></div><div class="faq-list">
      <details><summary>What is Aigents, in one sentence?</summary><p>Aigents is a platform for engineering students to present their skills and projects, prepare with practical AI tools, and connect with employers about paid work.</p></details>
      <details><summary>Do I need to be an AI expert?</summary><p>You can start by adding the skills and projects you already have. Practical engineering knowledge comes first; AI tools support tasks such as coding, analysis and documentation.</p></details>
      <details><summary>Does creating a profile guarantee a job?</summary><p>Creating a profile is a first step. A placement, start date and pay depend on a suitable opportunity and an agreement with the employer.</p></details>
      <details><summary>What happens after I create my profile?</summary><p>Your account saves your profile so you can return, edit it and view enquiries. It starts private. When you're ready, turn sharing on and send your profile link to employers. Your shared profile excludes your email address and academic grades. <a href="/signin">Sign in to your account</a> to manage your profile and sharing settings.</p></details>
      <details><summary>I'm an employer. Where do I start?</summary><p><a href="/employers">Send a project enquiry</a> with the skills you need and your preferred timing. It is saved in the Aigents team inbox. If you enquire through a student's shared profile, the student can also view your request in their inbox.</p></details>
    </div></div></section>
    <div class="wrap"><section class="closing"><div><h2>Your engineering career<br>starts with what you can do.</h2><p>Let's put your skills and projects in the picture.</p></div><a class="btn btn-light" href="/build">Create your student profile ${arrow}</a></section></div>
  </main>
  <footer class="footer"><div class="wrap footer-inner"><div><a class="brand" href="/" aria-label="Aigents home"><span class="brand-word">aigents<span>.</span></span></a><p class="footer-description">Engineering students. Practical AI skills. Paid work.</p></div><nav class="footer-links" aria-label="Footer navigation"><a href="/build">For students</a><a href="/employers">For employers</a><a href="/signin">Sign in</a><a href="/privacy">Privacy &amp; data</a><a href="mailto:deploy@aigents.au">Contact</a></nav></div></footer>
  <script>
    const menuButton=document.querySelector('.menu-button');
    const navigation=document.getElementById('main-navigation');
    function closeMenu(){navigation.classList.remove('open');menuButton.setAttribute('aria-expanded','false');menuButton.setAttribute('aria-label','Open navigation');}
    menuButton.addEventListener('click',()=>{const open=menuButton.getAttribute('aria-expanded')!=='true';navigation.classList.toggle('open',open);menuButton.setAttribute('aria-expanded',String(open));menuButton.setAttribute('aria-label',open?'Close navigation':'Open navigation');});
    navigation.querySelectorAll('a').forEach(link=>link.addEventListener('click',closeMenu));
    document.addEventListener('keydown',event=>{if(event.key==='Escape'&&menuButton.getAttribute('aria-expanded')==='true'){closeMenu();menuButton.focus();}});
    const audienceTabs=Array.from(document.querySelectorAll('[role="tab"]'));
    function selectAudience(id,focus=false){audienceTabs.forEach(tab=>{const selected=tab.id===id;tab.setAttribute('aria-selected',String(selected));tab.tabIndex=selected?0:-1;document.getElementById(tab.getAttribute('aria-controls')).hidden=!selected;if(selected&&focus)tab.focus();});}
    audienceTabs.forEach((tab,index)=>{tab.addEventListener('click',()=>selectAudience(tab.id));tab.addEventListener('keydown',event=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(event.key)){event.preventDefault();const next=event.key==='Home'?0:event.key==='End'?audienceTabs.length-1:(index+(event.key==='ArrowRight'?1:-1)+audienceTabs.length)%audienceTabs.length;selectAudience(audienceTabs[next].id,true);}});});
    document.querySelectorAll('[data-employer-link]').forEach(link=>link.addEventListener('click',()=>selectAudience('employer-tab')));
    document.querySelectorAll('a[href="#for-you"]:not([data-employer-link])').forEach(link=>link.addEventListener('click',()=>selectAudience('student-tab')));
  </script>
</body>
</html>`;
}
